ALTER TABLE absent_requests
    ADD COLUMN approved_by INTEGER DEFAULT NULL REFERENCES teachers (id),
    ADD COLUMN approved_at TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN rejected_by INTEGER DEFAULT NULL REFERENCES teachers (id),
    ADD COLUMN rejected_at TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    ADD COLUMN deleted_by INTEGER REFERENCES students (id) DEFAULT NULL,
;