ALTER TABLE IF EXISTS teachers
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    ADD COLUMN deleted_by INTEGER REFERENCES admins (id) DEFAULT NULL
;

ALTER TABLE IF EXISTS students
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    ADD COLUMN deleted_by INTEGER REFERENCES admins (id) DEFAULT NULL
;