ALTER TABLE IF EXISTS attendances
    ADD COLUMN time_in TIMESTAMP,
    ADD COLUMN time_out TIMESTAMP,
    ADD COLUMN created_by INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN updated_by INTEGER NULL DEFAULT NULL
;