version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
    - gocritic
    - unparam
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - gosec
  disable:
    - errcheck
  
linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
  gosec:
    severity: medium
    confidence: medium